import { mongoClient } from "@/lib/auth";
import { Sparkles } from "lucide-react";
import { GalleryClient } from "./gallery-client";

export const revalidate = 0; // Disable static rendering to always show fresh posts

async function getPosts() {
  try {
    const db = mongoClient.db("ugenAI");
    const posts = await db
      .collection("posts")
      .find({ status: "published" })
      .sort({ createdAt: -1 })
      .toArray();
      
    // Convert ObjectIds to strings to avoid Next.js warning
    return posts.map(post => ({
      ...post,
      _id: post._id.toString()
    }));
  } catch (error) {
    console.error("Failed to fetch gallery posts:", error);
    return [];
  }
}

export default async function UgenGalleryPage() {
  const posts = await getPosts();

  return (
    <div className="min-h-screen bg-ugen-bg pt-28 pb-16 px-6 selection:bg-ugen-primary/30">
      {/* Background Decor */}
      <div className="fixed inset-0 z-0 pointer-events-none overflow-hidden">
        <div className="absolute top-[-10%] left-[20%] w-[600px] h-[600px] bg-ugen-primary/10 rounded-full blur-[150px]" />
        <div className="absolute bottom-[-10%] right-[10%] w-[500px] h-[500px] bg-ugen-accent/10 rounded-full blur-[120px]" />
      </div>

      <div className="relative z-10 max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-ugen-primary/30 bg-ugen-primary/10 text-ugen-primary text-sm font-medium mb-6">
            <Sparkles size={16} />
            Community Gallery
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">
            Discover <span className="text-gradient">AI Masterpieces</span>
          </h1>
          <p className="text-white/60 text-lg max-w-2xl mx-auto">
            Explore breathtaking images generated by creators around the world using ugenAI.
          </p>
        </div>

        <GalleryClient initialPosts={posts as any} />
      </div>
    </div>
  );
}
