import { mongoClient } from "@/lib/auth";
import { Heart, Eye, Sparkles } from "lucide-react";
import Link from "next/link";

export const revalidate = 0; // Disable static rendering to always show fresh posts

async function getPosts() {
  try {
    const db = mongoClient.db("ugenAI");
    const posts = await db
      .collection("posts")
      .find({ status: "published" })
      .sort({ createdAt: -1 })
      .toArray();
      
    // Convert ObjectIds to strings to avoid Next.js warning
    return posts.map(post => ({
      ...post,
      _id: post._id.toString()
    }));
  } catch (error) {
    console.error("Failed to fetch gallery posts:", error);
    return [];
  }
}

export default async function UgenGalleryPage() {
  const posts = await getPosts();

  return (
    <div className="min-h-screen bg-ugen-bg pt-28 pb-16 px-6 selection:bg-ugen-primary/30">
      {/* Background Decor */}
      <div className="fixed inset-0 z-0 pointer-events-none overflow-hidden">
        <div className="absolute top-[-10%] left-[20%] w-[600px] h-[600px] bg-ugen-primary/10 rounded-full blur-[150px]" />
        <div className="absolute bottom-[-10%] right-[10%] w-[500px] h-[500px] bg-ugen-accent/10 rounded-full blur-[120px]" />
      </div>

      <div className="relative z-10 max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-ugen-primary/30 bg-ugen-primary/10 text-ugen-primary text-sm font-medium mb-6">
            <Sparkles size={16} />
            Community Gallery
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">
            Discover <span className="text-gradient">AI Masterpieces</span>
          </h1>
          <p className="text-white/60 text-lg max-w-2xl mx-auto">
            Explore breathtaking images generated by creators around the world using ugenAI.
          </p>
        </div>

        {posts.length === 0 ? (
          <div className="glass rounded-3xl p-12 text-center border border-white/10 max-w-2xl mx-auto mt-12">
            <div className="w-20 h-20 bg-white/5 rounded-full flex items-center justify-center mx-auto mb-6">
              <Sparkles className="w-10 h-10 text-white/30" />
            </div>
            <h3 className="text-xl font-bold text-white mb-2">No posts yet</h3>
            <p className="text-white/50 mb-8">Be the first to generate and share an amazing AI image with the community!</p>
            <Link 
              href="/generate-image"
              className="inline-flex items-center justify-center px-6 py-3 bg-gradient-to-r from-ugen-primary to-ugen-accent text-white font-medium rounded-full shadow-lg shadow-ugen-primary/20 hover:scale-105 transition-transform"
            >
              Generate Image
            </Link>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {posts.map((post: any) => (
              <div key={post._id} className="group relative glass rounded-2xl border border-white/10 overflow-hidden hover:border-white/20 transition-all duration-300">
                {/* Image */}
                <div className="aspect-[4/5] w-full overflow-hidden bg-black/40">
                  <img
                    src={post.image}
                    alt={post.title}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                  />
                </div>
                
                {/* Overlay Gradient for Text Readability */}
                <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/40 to-transparent opacity-80" />

                {/* Content Area (Absolute positioned on bottom) */}
                <div className="absolute bottom-0 left-0 right-0 p-5 flex flex-col justify-end">
                  <div className="flex items-center gap-2 mb-3">
                    <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-1 rounded-md bg-white/10 text-white/90 backdrop-blur-md">
                      {post.category}
                    </span>
                  </div>
                  
                  <h3 className="text-white font-bold text-lg leading-tight mb-3 line-clamp-2">
                    {post.title}
                  </h3>
                  
                  <div className="flex items-center justify-between">
                    {/* User Info */}
                    <div className="flex items-center gap-2">
                      <div className="w-6 h-6 rounded-full bg-white/20 overflow-hidden flex items-center justify-center flex-shrink-0">
                        {post.userImage ? (
                          <img src={post.userImage} alt={post.userName} className="w-full h-full object-cover" />
                        ) : (
                          <span className="text-[10px] font-bold text-white">{post.userName.charAt(0).toUpperCase()}</span>
                        )}
                      </div>
                      <div className="flex flex-col">
                        <span className="text-xs font-medium text-white/90 truncate max-w-[100px]">{post.userName}</span>
                        <span className="text-[10px] text-white/50">{new Date(post.createdAt).toLocaleDateString()}</span>
                      </div>
                    </div>

                    {/* Stats */}
                    <div className="flex items-center gap-3 text-white/60">
                      <div className="flex items-center gap-1">
                        <Heart className="w-3.5 h-3.5" />
                        <span className="text-xs font-medium">{post.likes || 0}</span>
                      </div>
                      <div className="flex items-center gap-1">
                        <Eye className="w-3.5 h-3.5" />
                        <span className="text-xs font-medium">{post.views || 0}</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
